# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from benny_service import benny_service_pb2 as benny__service_dot_benny__service__pb2


class AccountServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReadUserById = channel.unary_unary(
        '/sono.AccountService/ReadUserById',
        request_serializer=benny__service_dot_benny__service__pb2.UserIdParams.SerializeToString,
        response_deserializer=benny__service_dot_benny__service__pb2.UserResponse.FromString,
        )
    self.ReadUserByEmail = channel.unary_unary(
        '/sono.AccountService/ReadUserByEmail',
        request_serializer=benny__service_dot_benny__service__pb2.UserEmailParams.SerializeToString,
        response_deserializer=benny__service_dot_benny__service__pb2.UserResponse.FromString,
        )
    self.Paginate = channel.unary_unary(
        '/sono.AccountService/Paginate',
        request_serializer=benny__service_dot_benny__service__pb2.PaginateParams.SerializeToString,
        response_deserializer=benny__service_dot_benny__service__pb2.PaginateResponse.FromString,
        )


class AccountServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ReadUserById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadUserByEmail(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Paginate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReadUserById': grpc.unary_unary_rpc_method_handler(
          servicer.ReadUserById,
          request_deserializer=benny__service_dot_benny__service__pb2.UserIdParams.FromString,
          response_serializer=benny__service_dot_benny__service__pb2.UserResponse.SerializeToString,
      ),
      'ReadUserByEmail': grpc.unary_unary_rpc_method_handler(
          servicer.ReadUserByEmail,
          request_deserializer=benny__service_dot_benny__service__pb2.UserEmailParams.FromString,
          response_serializer=benny__service_dot_benny__service__pb2.UserResponse.SerializeToString,
      ),
      'Paginate': grpc.unary_unary_rpc_method_handler(
          servicer.Paginate,
          request_deserializer=benny__service_dot_benny__service__pb2.PaginateParams.FromString,
          response_serializer=benny__service_dot_benny__service__pb2.PaginateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sono.AccountService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
